const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
SESSION_ID: process.env.SESSION_ID === undefined ? 'SUPUN-MD=w5gX0BbC#e9tuVmxT_uLi-CieiUM7tcW4HcbwJBqp4kRFFlNLQRM' : process.env.SESSION_ID,
PREFIX: process.env.PREFIX || '.' ,
PORT: process.env.PORT === undefined ? "8000" : process.env.PORT,
OWNER_NUMBER: process.env.OWNER_NUMBER === undefined ? '94719036654' : process.env.OWNER_NUMBER,
MODE: process.env.MODE === undefined ?"groups" : process.env.MODE,
BUTTON: process.env.BUTTON === undefined ?"true" : process.env.BUTTON,
AUTO_READ_STATUS: process.env.AUTO_READ_STATUS === undefined ?"false" : process.env.AUTO_READ_STATUS,
AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT === undefined ?"false" : process.env.AUTO_STATUS_REACT,
AUTO_VOICE: process.env.AUTO_VOICE === undefined ? "false" : process.env.AUTO_VOICE,
AUTO_REPLY: process.env.AUTO_REPLY === undefined ? "false" : process.env.AUTO_REPLY,
AUTO_STICKER: process.env.AUTO_STICKER === undefined ? "false" : process.env.AUTO_STICKER,
ANTI_BAD: process.env.ANTI_BAD === undefined ? "false" : process.env.ANTI_BAD,
ANTI_LINK: process.env.ANTI_LINK === undefined ? "false" : process.env.ANTI_LINK,
ANTI_CALL: process.env.ANTI_CALL === undefined ? "true" : process.env.ANTI_CALL, 
ANTI_BOT: process.env.ANTI_BOT === undefined ? "false" : process.env.ANTI_BOT,   
ANTI_DELETE: process.env.ANTI_DELETE === undefined ? 'true' : process.env.ANTI_DELETE,
DELETEMSGSENDTO : process.env.DELETEMSGSENDTO === undefined ? 'false' : process.env.DELETEMSGSENDTO,
WELCOME_GOODBYE: process.env.WELCOME_GOODBYE === undefined ? 'false' : process.env.WELCOME_GOODBYE,
ADMIN_EVENT: process.env.ADMIN_EVENT === undefined ? 'false' : process.env.ADMIN_EVENT,
AI_CHAT: process.env.AI_CHAT === undefined ? "false" : process.env.AI_CHAT,
ALLWAYS_OFFLINE: process.env.ALLWAYS_OFFLINE === undefined ? "false" : process.env.ALLWAYS_OFFLINE,
ALLWAYS_ONLINE: process.env.ALLWAYS_ONLINE === undefined ? "false" : process.env.ALLWAYS_ONLINE,
AUTO_READ_CMD: process.env.AUTO_READ_CMD === undefined ? "false" : process.env.AUTO_READ_CMD,
ALWAYS_RECORDING: process.env.ALWAYS_RECORDING === undefined ? "false" : process.env.ALWAYS_RECORDING,
ALWAYS_TYPING: process.env.ALWAYS_TYPING === undefined ? "false" : process.env.ALWAYS_TYPING,
AUTO_BIO: process.env.AUTO_BIO === undefined ? "false" : process.env.AUTO_BIO,
AUTO_REACT: process.env.AUTO_REACT === undefined ? "false" : process.env.AUTO_REACT,
OWNER_REACT: process.env.OWNER_REACT === undefined ? "true" : process.env.OWNER_REACT,
HEART_REACT: process.env.HEART_REACT === undefined ? "false" : process.env.HEART_REACT,
MAX_SIZE: process.env.MAX_SIZE === undefined ? "1900" : process.env.MAX_SIZE,
AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY === undefined ? "false" : process.env.AUTO_STATUS_REPLY,
AUTO_STATUS__MSG: process.env.AUTO_STATUS__MSG === undefined ? "`𝒀𝒐𝒖𝒓 𝒔𝒕𝒂𝒕𝒖𝒔 𝒔𝒆𝒆𝒏 𝒋𝒖𝒔𝒕 𝒏𝒐𝒘 𝒃𝒚 ♥️🌸⃝ALFAᥫ᭡👑`" : process.env.AUTO_STATUS__MSG,
WELCOME_MG: process.env.WELCOME_MG === undefined ? "*Enjoy your stay and follow the rules! 😊*" : process.env.WELCOME_MG,
LEAVE_MG: process.env.LEAVE_MG === undefined ? "*Hope to see you again! 🥺*" : process.env.LEAVE_MG,
PROMOTE_MG: process.env.PROMOTE_MG === undefined ? "You have been *promoted* to *admin* 🥳" : process.env.PROMOTE_MG,
DEMOTE_MG: process.env.DEMOTE_MG === undefined ? "You have been *demoted* from *admin* 😬" : process.env.DEMOTE_MG,
AUTO_ADD_Country_Code: process.env.AUTO_ADD_Country_Code === undefined ? "94" : process.env.AUTO_ADD_Country_Code,
AUTO_NEWS_SENDER: process.env.AUTO_NEWS_SENDER === undefined ? "false" : process.env.AUTO_NEWS_SENDER,
AUTO_TIKTOK_SENDER: process.env.AUTO_TIKTOK_SENDER === undefined ? "false" : process.env.AUTO_TIKTOK_SENDER,
AUTO_ANIM_SENDER: process.env.AUTO_ANIM_SENDER === undefined ? "false" : process.env.AUTO_ANIM_SENDER,
FOOTER: process.env.FOOTER === undefined ? "✨️💗 > ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʙʟᴀᴄᴋ ᴀʟꜰᴀ ²⁰²⁵᭄ 💗✨️" : process.env.FOOTER,
LANG: process.env.LANG === undefined ? "SI" : process.env.LANG, // SI OR EN
MOVIE_NAME: process.env.MOVIE_NAME === undefined ? "🇱🇰 ʙʟᴀᴄᴋ ᴀʟꜰᴀ ᴏꜰꜰɪᴄɪᴀʟ 🇱🇰" : process.env.MOVIE_NAME,
MOVIE_JID: process.env.MOVIE_JID === undefined ? "120363270086174844@newsletter" : process.env.MOVIE_JID,
SEEDR_MAIL: process.env.SEEDR_MAIL === undefined ? "supunfernando0089@gmail.com" : process.env.SEEDR_MAIL,       
SEEDR_PASSWORD: process.env.SEEDR_PASSWORD === undefined ? "Supun@13642" : process.env.SEEDR_PASSWORD,
MenuType: process.env.MenuType === undefined ? "v3" : process.env.MenuType,
AliveType: process.env.AliveType === undefined ? "v2" : process.env.AliveType,
ReplyType: process.env.ReplyType === undefined ? "v1" : process.env.ReplyType,
TIKTOKSE: process.env.TIKTOKSE === undefined ? "sinhala status wadan" : process.env.TIKTOKSE,
NEWS_SEND_JID: process.env.NEWS_SEND_JID === undefined ? "120363399205146445@newsletter" : process.env.NEWS_SEND_JID,
TIKTOK_SEND_JID: process.env.TIKTOK_SEND_JID === undefined ? "120363270086174844@newsletter" : process.env.TIKTOK_SEND_JID,
ANIM_SEND_JID: process.env.ANIM_SEND_JID === undefined ? "120363270086174844@newsletter" : process.env.ANIM_SEND_JID,
BAD_NO_BLOCK: process.env.BAD_NO_BLOCK === undefined ? "false" : process.env.BAD_NO_BLOCK,
AUTO_BLOCK: process.env.AUTO_BLOCK === undefined ? "false" : process.env.AUTO_BLOCK,
ALIVE_MG: process.env.ALIVE_MG === undefined ? "*Hello , I am alive now!!*" : process.env.ALIVE_MG,
MENU_MG: process.env.MENU_MG === undefined ? "*Hello User..\nSupun Md User Commad List*" : process.env.MENU_MG,
ALIVE_LOGO: process.env.ALIVE_LOGO === undefined ? "https://files.catbox.moe/thqsmp.jpg" : process.env.ALIVE_LOGO,
MENU_LOGO: process.env.MENU_LOGO === undefined ? "https://files.catbox.moe/w77zu5.jpg" : process.env.MENU_LOGO,
SEEDR_MAIL: process.env.SEEDR_MAIL === undefined ? "supunfernando0089@gmail.com" : process.env.SEEDR_MAIL,       
SEEDR_PASSWORD: process.env.SEEDR_PASSWORD === undefined ? "Supun@13642" : process.env.SEEDR_PASSWORD,
POSTGRESQL_URL: process.env.POSTGRESQL_URL === undefined ? 'postgresql://supunmd_user:GFZWS3M3Ib1lOSMjIlEWYIWts40q4VZv@dpg-cvlm8e2dbo4c7399ph60-a.oregon-postgres.render.com/supunmd' : process.env.POSTGRESQL_URL,
OMDB_API_KEY: process.env.OMDB_API_KEY === undefined ? '76cb7f39' : process.env.OMDB_API_KEY,
   };
    
